### ISSUE TITLE
Change cwd automatically when selecting a project

### ISSUE THREAD

**Issue by KJone1** [CWood-sdf/spaceport.nvim#4]
For context, when I enter nvim from my home directory and select a saved project, the cwd stays in the home directory.
I am not sure if there is an option to change the cwd when selecting a project but the default is false.
If not, could it be added as a feature?
I could not find any reference to this in the docs.
Much appreciated great plugin :D

**Comment by CWood-sdf** [comment]
Can I have some additional context on the problem? what command/function are you calling that is returning the wrong cwd?

Spaceport automatically sets neovim's cwd when navigating to a directory but not a file, so that might be the problem

**Comment by KJone1** [comment]
I start nvim from my home dir /home/kj and spaceport opens:

![2024-02-23T11:22:06,640936456+02:00](https://github.com/CWood-sdf/spaceport.nvim/assets/58522694/d450c170-2749-4ec3-841e-5d0d8ef9f164)

when selecting '1p' telescope-file-browser opens:

![2024-02-23T11:22:30,221173515+02:00](https://github.com/CWood-sdf/spaceport.nvim/assets/58522694/f0279251-1180-4abd-8ade-46eb9b40e2ab)

after opening a file and running :pwd the output is:

![2024-02-23T11:23:01,112651476+02:00](https://github.com/CWood-sdf/spaceport.nvim/assets/58522694/649b05b6-60d2-4b52-9e83-c5ca57d1716e)

am i missing something?

**Comment by CWood-sdf** [comment]
Ok so I think I know what is going wrong here:

1. When spaceport opens a file, the cwd is not set because it is really hard to correctly determine what the cwd should be when looking at a file path

2. When spaceport encounters an error with reading the json data file, it sets isDir to false for everything (this is what I believe the problem is)

I just wrote a fix for this, but before I publish it, I would like to confirm that that is what is happening with your setup. So could you open the file ~/.local/share/nvim/spaceport.json, format it so that it looks nice, and then confirm that the element with the key of "/home/kj/DEV/dotfiles" has the property isDir set to false?

For example, this is what my ~/.config/nvim folder looks like in the entry:

![image](https://github.com/CWood-sdf/spaceport.nvim/assets/98367120/378ab10f-c61a-4dd7-bc32-3da7790329b3)

**Comment by KJone1** [comment]
it seems that everything is set to false 

![2024-02-23T21:50:16,083900097+02:00](https://github.com/CWood-sdf/spaceport.nvim/assets/58522694/5f6e01fa-5760-464c-a515-48a9bd83af6e)

including my pins:

``` 
 "/home/kj/DEV/sddm-dark-chocolate/": {
    "isDir": false,
    "pinNumber": 2,
    "time": 1706986007
  },
```
```
  "/home/kj/DEV/Ansible_config/": {
    "isDir": false,
    "pinNumber": 3,
    "time": 1707561463
  },

```
```
  "/home/kj/DEV/dotfiles/": {
    "isDir": false,
    "pinNumber": 1,
    "time": 1708711627
  },

```

**Comment by CWood-sdf** [comment]
Ok i just published the change, it should set isDir to the proper value when you open up neovim now. If it still does not work, let me know, otherwise you can just close the issue

**Comment by KJone1** [comment]
I recreated the config file and it works now, thanks :)
closing.
